name: Fullstack-Lab-Test-Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing required packages
        run: npm install
      - name: Running Linter configurations
        run: npm run lint
      - name: Running Tests
        run: CI=true npm run test
      - name: Building the code
        run: npm run build
      - name: Creating Artifact
        run: tar -cvf fullstack-node-app.tar.gz ./*
      - name: Copying Artifact to destination server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "fullstack-node-app.tar.gz"
          target: "/tmp/fullstack-node-app"
      - name: Extracting and running the application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /tmp/fullstack-node-app
            tar -xvf fullstack-node-app.tar.gz
            cd /tmp/fullstack-node-app && pm2 start npm -- run start
